/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal development. It is committed here
// so type-checking works before the first local `next dev` run.
